### ISSUE TITLE
Error 522 for Foundation Zurb Inliner v2 

### ISSUE THREAD

**Issue by edward-frontier** [foundation/foundation-marketing#10]
Hi I can’t seem to access this URL anymore with it erroring out a Error 522:
https://foundation.zurb.com/emails.html

I need this to inline my Foundation 5 emails still.

Hoping someone is able to help!

EDIT: this Inliner doesn’t seem to be working too (only receiving a Loading.. message): https://get.foundation/emails/inliner.html

Thanks,
Edward

**Comment by bopbebop** [comment]
Please, i need to know if this is a temporal problem or if you are going to remain giving service. 

Thanks!

**Comment by DanielRuf** [comment]
Hi, you are using the old website. The new website is at https://get.foundation and the inliner is at https://get.foundation/emails/inliner-v2.html

**Comment by edward-frontier** [comment]
Hi I'm getting a Page Not Found for that new inliner URL.

**Comment by DanielRuf** [comment]
Hi @edward-frontier, the new URL is https://get.foundation/emails/inliner.html

**Comment by DanielRuf** [comment]
Sorry, forgot to mention that I have removed the old inliner versions and renamed the file.
